#volume

#build . for app

services:
  app:
    build: .
    depends_on: 
      - web
      - datadog-agent
    volumes:
      - .:/app
    environment:
      - DD_TRACE_AGENT_URL=http://datadog-agent:8126/ 
      - DD_LOGS_INJECTION=true
      - DD_ENV=prod
      - DD_SERVICE=gameday
      - DD_VERSION=1.1
  web:
    image: nginx
    volumes:
     - ./templates:/etc/nginx/templates
    ports:
     - "8080:80"

  datadog-agent:
    image: datadog/agent
    environment:
     - DD_API_KEY=<API-KEY>
     - DD_SITE=datadoghq.com
     - DD_LOGS_ENABLED=true
     - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true 
     - DD_LOGS_CONFIG_DOCKER_CONTAINER_USE_FILE=true 
     - DD_CONTAINER_EXCLUDE="name:datadog-agent" 
     - DD_APM_ENABLED=true 
     - DD_APM_NON_LOCAL_TRAFFIC=true 
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro 
     - /var/lib/docker/containers:/var/lib/docker/containers:ro
     - /opt/datadog-agent/run:/opt/datadog-agent/run:rw   

    
    
  
