#volume

#build . for app

services:
  app:
    build: .
    depends_on: 
      - web
    volumes:
      - .:/app
  web:
    image: nginx
    volumes:
     - ./templates:/etc/nginx/templates
    ports:
     - "8080:80"
