#volume

#build . for app

services:
  app:
    build: .
    depends_on: 
      - web
    volumes:
      - .:/app
    environment:
      - DD_AGENT_HOST=172.17.0.1
      - DD_TRACE_AGENT_PORT=8126
      - DD_LOGS_INJECTION=true
      - DD_ENV=prod
      - DD_SERVICE=gameday
      - DD_VERSION=1.1
  web:
    image: nginx
    volumes:
     - ./templates:/etc/nginx/templates
    ports:
     - "8080:80"
